name: Run TestsAdd commentMore actions
on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      build:
        context: .
        dockerfile: docker/app/Dockerfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true
      - name: Upload Playwright test report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report